// build-graph — Phase 2. Compile the genealogy graph and emit the offline
// artifacts. Uses the SHARED compiler (graph/compile.js) so it can never diverge
// from what the Function builds at runtime.
//
// Sources:
//   graph/seed-targaryen.json  — hand-curated, VERIFIED. Source of truth.
//   graph/reviewed-edges.json  — approved LLM-extracted edges (from
//                                ingest/review-edges.js). Optional; [] by default.
//
// Emits (both are DERIVED — gitignored; regenerate before a D1 load or to
// inspect the compiled graph):
//   graph/graph.json  — the compiled graph, for inspection / debugging.
//   graph/edges.sql   — idempotent D1 load (nodes + edges) for the robust backend.
//
// Usage:
//   node ingest/build-graph.js            # compile + report
//   node ingest/build-graph.js --strict   # non-zero exit on any validation warning
//
// Load into D1:
//   npx wrangler d1 execute iron-throne-graph --remote --file=graph/edges.sql

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { buildGraph } from "../graph/compile.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const SEED_PATH = join(ROOT, "graph", "seed-targaryen.json");
const REVIEWED_PATH = join(ROOT, "graph", "reviewed-edges.json");
const GRAPH_OUT = join(ROOT, "graph", "graph.json");
const SQL_OUT = join(ROOT, "graph", "edges.sql");
const STRICT = process.argv.includes("--strict");

const sqlStr = (s) => `'${String(s).replace(/'/g, "''")}'`;

function toSql(nodes, edges) {
  const lines = [
    "-- Generated by ingest/build-graph.js — idempotent D1 load (iron-throne-graph).",
    "PRAGMA foreign_keys = OFF;",
    "DELETE FROM edges;",
    "DELETE FROM nodes;",
    "",
  ];
  for (const n of Object.values(nodes)) {
    lines.push(`INSERT INTO nodes (id, name, house, gender) VALUES (${sqlStr(n.id)}, ${sqlStr(n.name)}, ${n.house ? sqlStr(n.house) : "NULL"}, ${n.gender ? sqlStr(n.gender) : "NULL"});`);
  }
  lines.push("");
  for (const e of edges) {
    if (e.type === "parent") lines.push(`INSERT INTO edges (type, src, dst, source) VALUES ('parent', ${sqlStr(e.from)}, ${sqlStr(e.to)}, ${sqlStr(e.source || "seed")});`);
    else if (e.type === "spouse") lines.push(`INSERT INTO edges (type, src, dst, source) VALUES ('spouse', ${sqlStr(e.a)}, ${sqlStr(e.b)}, ${sqlStr(e.source || "seed")});`);
  }
  return lines.join("\n") + "\n";
}

async function main() {
  const seed = JSON.parse(await readFile(SEED_PATH, "utf8"));
  const reviewed = existsSync(REVIEWED_PATH) ? JSON.parse(await readFile(REVIEWED_PATH, "utf8")) : [];

  const g = buildGraph(seed, reviewed);

  // Persist the compiled graph (minus the transient `edges`/`warnings` fields).
  const { edges, warnings, ...persist } = g;
  persist.meta = { ...persist.meta, builtAt: new Date().toISOString() };
  await writeFile(GRAPH_OUT, JSON.stringify(persist, null, 2) + "\n");
  await writeFile(SQL_OUT, toSql(g.nodes, edges));

  console.log(`[build-graph] nodes=${g.meta.counts.nodes} parent=${g.meta.counts.parentEdges} spouse=${g.meta.counts.spouseEdges}`);
  console.log(`[build-graph] reviewed edges merged: ${g.meta.counts.addedFromReview}${reviewed.length ? "" : " (graph/reviewed-edges.json absent or empty)"}`);
  console.log(`[build-graph] wrote graph/graph.json + graph/edges.sql`);

  if (warnings.length) {
    console.log(`\n[build-graph] ${warnings.length} validation warning(s):`);
    for (const w of warnings) console.log(`  - ${w}`);
    if (STRICT) process.exit(1);
  } else {
    console.log("[build-graph] validation clean.");
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
